update for semester WS16/17 (make jannikpeters commit run)
knub/onehundredandeighty pull request #36
Opened 2017-02-06 12:55 UTC by Miroka96

Hopefully I clicked the right things
When will the official 180 will be up again? Who can I ask if help is needed?

2017-02-06 20:32 UTC, knub commented on js/data.js
> +		dozent: ["Prof. Dr. Robert Hirschfeld ",],
Syntax error, trailing comma.

2017-02-06 20:37 UTC, knub requested changes

2017-02-06 20:37 UTC, knub commented on js/data.js
> +	softwaremodlaritaet: {
Typo.

2017-02-06 20:37 UTC, knub commented on js/logic.js
> +	startswith: "SS17",
That's not possible. It cannot start with a semester that does not exist yet.
Also, it does not make sense to set this to a summer semester, as no HPI student starts his bachelor in the summer semester.

2017-02-06 20:37 UTC, knub commented on js/data.js
> +		semester: [ws15_16, ws16_17],
For all those cases, were you just added "ws16_17": Have you checked, that the Vertiefungsgebiete match the ones from the earlier semesters?

2017-02-06 20:40 UTC, knub commented
> When will the official 180 will be up again? Who can I ask if you need help?
I do not know, I have no influence on that. You can try asking the FSR and/or the website club. Also, if you need it now, you can simply run it locally on your branch.

2017-02-06 21:10 UTC, Miroka96 commented
Maybe I have forked the wrong branch of jannikpeters... I will have a look at all changes and try some settings, also depending the new Studienordnung. Time to learn JavaScript.

2019-07-10 09:45 UTC, knub commented
Closing as it's inactive.

2019-07-10 09:45 UTC, closed without merging